title: "Architecture Design & Module Implementation"
description: Embedded Control System Design Guideline
baseurl: "/MyTest_Jtd" # the subpath of your site, e.g. /blog
url: "https://wootaik.github.io" 

remote_theme: pmarsceill/just-the-docs

color_scheme: "light"

search_enabled: true

# Enable or disable heading anchors
heading_anchors: true


